# docker-compose.yaml (updated)
version: '3.8'
services:
  godeep:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - ACTIVELOOP_TOKEN=${ACTIVELOOP_TOKEN}
      - ACTIVELOOP_ORG_ID=${ACTIVELOOP_ORG_ID}
      - ACTIVELOOP_DATASET_PATH=${ACTIVELOOP_DATASET_PATH}
    dns:
      - 8.8.8.8  # Google DNS
      - 1.1.1.1  # Cloudflare DNS
    network_mode: "host"
